const fs = require('fs');
const path = require('path');

const root = __dirname;
const shellPath = path.join(root, 'ep_weather_provider_shell.html');
const dataPath = path.join(root, 'ep_weather_provider_data.js');
const uiPath = path.join(root, 'ep_weather_provider_ui.js');
const outputPath = path.join(root, 'ep_weather_provider_open_meteo_html.h');

function readNormalized(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n').trimEnd();
}

function buildHtml() {
  const shell = readNormalized(shellPath);
  const data = readNormalized(dataPath);
  const ui = readNormalized(uiPath);
  return shell
    .replace('/*__EP_WEATHER_DATA__*/', data)
    .replace('/*__EP_WEATHER_UI__*/', ui) + '\n';
}

function cStringLine(line) {
  return `L${JSON.stringify(`${line}\n`)}`;
}

function buildHeader(html) {
  const literals = html.split('\n');
  literals.pop();
  return [
    '#ifndef _H_EP_WEATHER_PROVIDER_OPEN_METEO_HTML_H_',
    '#define _H_EP_WEATHER_PROVIDER_OPEN_METEO_HTML_H_',
    '#include <Windows.h>',
    '',
    '// Generated by generate_weather_provider_header.js. Edit the HTML/JS source files instead.',
    'static const WCHAR ep_weather_provider_open_meteo_html[] =',
    ...literals.map(cStringLine),
    ';',
    '#endif',
    ''
  ].join('\n');
}

if (require.main === module) {
  const expected = buildHeader(buildHtml());
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(outputPath) ? readNormalized(outputPath) + '\n' : '';
    if (actual !== expected) {
      console.error('Generated weather provider header is out of date.');
      process.exit(1);
    }
  } else {
    fs.writeFileSync(outputPath, expected, 'utf8');
  }
}

module.exports = { buildHeader, buildHtml };
