const fs = require('fs');
const path = require('path');

const root = __dirname;
const shellPath = path.join(root, 'ep_weather_provider_shell.html');
const dataPath = path.join(root, 'ep_weather_provider_data.js');
const iconsPath = path.join(root, 'ep_weather_provider_icons.js');
const uiPath = path.join(root, 'ep_weather_provider_ui.js');
const iconFontPath = path.join(root, 'assets', 'qweather-icons-1.8.0.woff2');
const iconMapPath = path.join(root, 'assets', 'qweather-icons-1.8.0.json');
const outputPath = path.join(root, 'ep_weather_provider_open_meteo_html.h');
const MAX_C_LITERAL_LENGTH = 8000;
const WEATHER_ICON_CODES = Object.freeze([
  '100', '101', '102', '103', '104', '150', '151', '152', '153',
  '300', '301', '302', '303', '304', '305', '306', '307', '308', '309',
  '310', '311', '312', '313', '314', '315', '316', '317', '318', '350',
  '351', '399', '400', '401', '402', '403', '404', '405', '406', '407',
  '408', '409', '410', '456', '457', '499', '500', '501', '502', '503',
  '504', '507', '508', '509', '510', '511', '512', '513', '514', '515',
  '800', '801', '802', '803', '804', '805', '806', '807', '900', '901', '999'
]);

function readNormalized(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n').trimEnd();
}

function replaceMarker(source, marker, value) {
  const first = source.indexOf(marker);
  if (first < 0 || source.indexOf(marker, first + marker.length) >= 0) {
    throw new Error(`Expected exactly one ${marker} marker.`);
  }
  return source.replace(marker, value);
}

function readIconMap() {
  const map = JSON.parse(readNormalized(iconMapPath));
  if (!map || typeof map !== 'object' || Array.isArray(map)) {
    throw new Error('QWeather icon map must be an object.');
  }
  for (const [name, codePoint] of Object.entries(map)) {
    if (!name || !Number.isInteger(codePoint) || codePoint < 0) {
      throw new Error(`Invalid QWeather icon mapping: ${name}`);
    }
  }
  for (const name of ['100', '100-fill', '999']) {
    if (!Number.isInteger(map[name])) throw new Error(`Missing QWeather icon: ${name}`);
  }
  return map;
}

function embeddedIconFontCss() {
  const base64 = fs.readFileSync(iconFontPath).toString('base64');
  if (!base64) throw new Error('QWeather icon font is empty.');
  return `@font-face { font-family: "QWeather Icons"; src: url("data:font/woff2;base64,${base64}") format("woff2"); font-display: block; }`;
}

function weatherIconMap() {
  const source = readIconMap();
  const result = Object.create(null);
  for (const code of WEATHER_ICON_CODES) {
    if (!Number.isInteger(source[code])) throw new Error(`Missing QWeather weather icon: ${code}`);
    result[code] = source[code];
    if (Number.isInteger(source[`${code}-fill`])) result[`${code}-fill`] = source[`${code}-fill`];
  }
  return result;
}

function buildHtml() {
  const shell = readNormalized(shellPath);
  const data = readNormalized(dataPath);
  const icons = readNormalized(iconsPath);
  const ui = readNormalized(uiPath);
  const iconMap = `const QWEATHER_ICON_GLYPHS = Object.freeze(${JSON.stringify(weatherIconMap())});`;
  let html = replaceMarker(shell, '/*__EP_QWEATHER_ICON_FONT__*/', embeddedIconFontCss());
  html = replaceMarker(html, '/*__EP_WEATHER_DATA__*/', data);
  html = replaceMarker(html, '/*__EP_WEATHER_ICONS__*/', icons);
  html = replaceMarker(html, '/*__EP_QWEATHER_ICON_MAP__*/', iconMap);
  html = replaceMarker(html, '/*__EP_WEATHER_UI__*/', ui);
  return html + '\n';
}

function cStringLiterals(html) {
  const literals = [];
  for (const line of html.match(/[^\n]*\n/g) || []) {
    for (let offset = 0; offset < line.length; offset += MAX_C_LITERAL_LENGTH) {
      literals.push(`L${JSON.stringify(line.slice(offset, offset + MAX_C_LITERAL_LENGTH))}`);
    }
  }
  return literals;
}

function buildHeader(html) {
  return [
    '#ifndef _H_EP_WEATHER_PROVIDER_OPEN_METEO_HTML_H_',
    '#define _H_EP_WEATHER_PROVIDER_OPEN_METEO_HTML_H_',
    '#include <Windows.h>',
    '',
    '// Generated by generate_weather_provider_header.js. Edit the HTML/JS source files instead.',
    'static const WCHAR ep_weather_provider_open_meteo_html[] =',
    ...cStringLiterals(html),
    ';',
    '#endif',
    ''
  ].join('\n');
}

if (require.main === module) {
  const expected = buildHeader(buildHtml());
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(outputPath) ? readNormalized(outputPath) + '\n' : '';
    if (actual !== expected) {
      console.error('Generated weather provider header is out of date.');
      process.exit(1);
    }
  } else {
    fs.writeFileSync(outputPath, expected, 'utf8');
  }
}

module.exports = { buildHeader, buildHtml, readIconMap, weatherIconMap };
